name: Backend CI + Manual Deploy

on:
  push:
    branches: [main]
  pull_request: 
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.14.0'

      - name: Install dependencies
        run: npm install
      
      - name: Lint (Optional)
        run: npm run lint
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: ${{ success() }}
    steps:
      - name: Deploy to Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}